// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username,
    passwdhash,
    email
) VALUES (
    $1, $2, $3
)
`

type CreateUserParams struct {
	Username   string `json:"username"`
	Passwdhash string `json:"passwdhash"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Passwdhash, arg.Email)
	return err
}

const loginUserWithUsername = `-- name: LoginUserWithUsername :one
SELECT username, passwdhash FROM users WHERE username = $1
`

type LoginUserWithUsernameRow struct {
	Username   string `json:"username"`
	Passwdhash string `json:"passwdhash"`
}

func (q *Queries) LoginUserWithUsername(ctx context.Context, username string) (LoginUserWithUsernameRow, error) {
	row := q.db.QueryRow(ctx, loginUserWithUsername, username)
	var i LoginUserWithUsernameRow
	err := row.Scan(&i.Username, &i.Passwdhash)
	return i, err
}
